# Generated by Django 4.1 on 2022-12-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='Без темы', max_length=255, verbose_name='Тема')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('answer', models.TextField(default='Сообщение доставлено', verbose_name='Ответ')),
                ('time_quest', models.DateTimeField(auto_now=True, verbose_name='Время вопроса')),
                ('time_answer', models.DateTimeField(auto_now=True, verbose_name='Время ответа')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
