# Generated by Django 4.1 on 2022-12-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_feedback_alter_news_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='topic',
            new_name='title',
        ),
    ]
